version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APACHE_PORT=80
    volumes:
      - ./api:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: satoshi
      MYSQL_ROOT_PASSWORD: S3nh-a
      MYSQL_DATABASE: btc_prices
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: